# Generated by Django 5.2.6 on 2025-12-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('check', 'Check'), ('other', 'Other')], default='bank_transfer', max_length=20, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='payment_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('commission', 'Commission')], default='monthly', max_length=20, null=True),
        ),
    ]
