# Generated by Django 5.2.6 on 2026-01-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_employee_payment_method_alter_employee_payment_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
