# Generated by Django 5.2.6 on 2025-10-08 21:24

import django.db.models.deletion
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='Unique identifier for the tenant, used ni URLs and subdomains', unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=200)),
                ('legal_name', models.CharField(help_text='Legal company name', max_length=200)),
                ('document', models.CharField(help_text='Unique identifier like SSN or Tax ID, CPF or CNPJ0', max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('entreprise', 'Enterprise')], default='free', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settings', models.JSONField(default=dict)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tenants',
                'indexes': [models.Index(fields=['slug'], name='tenants_slug_3181c2_idx'), models.Index(fields=['is_active', 'plan'], name='tenants_is_acti_c48360_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner')], default='user', max_length=30)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_accepted', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_invitations',
                'indexes': [models.Index(fields=['token'], name='tenant_invi_token_8b1449_idx'), models.Index(fields=['tenant', 'email', 'expires_at'], name='tenant_invi_tenant__4608ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('manager', 'Manager'), ('user', 'User'), ('viewer', 'Viewer')], default='user', max_length=30)),
                ('is_owner', models.BooleanField(default=False)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_access', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_users',
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='tenant_user_tenant__068a9b_idx'), models.Index(fields=['user', 'is_active'], name='tenant_user_user_id_088718_idx')],
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
