# Generated by Django 5.2.6 on 2025-11-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
