# Generated by Django 5.2.6 on 2025-11-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='document',
            field=models.CharField(help_text='Unique identifier like SSN or Tax ID, CPF or CNPJ', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='settings',
            field=models.JSONField(default=None, null=True),
        ),
    ]
