# Generated by Django 5.2.6 on 2025-11-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_address_alter_tenant_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='settings',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
