# Generated by Django 5.2.6 on 2025-11-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenant_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
