# Generated by Django 5.2.6 on 2025-11-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='document_number',
            field=models.CharField(blank=True, help_text='Unique identifier like SSN or Tax ID, CPF or CNPJ', max_length=30, null=True),
        ),
    ]
