# Generated by Django 5.2.6 on 2026-01-15 11:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import fleet.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0003_alter_employee_birth_date'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, help_text='Vehicle photo', null=True, upload_to=fleet.models.Vehicle.vehicle_photo_path)),
                ('type', models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('trailer', 'Trailer'), ('semi_trailer', 'Semi Trailer'), ('pickup', 'Pickup'), ('motorcycle', 'Motorcycle'), ('SUV', 'SUV'), ('minivan', 'Minivan'), ('sedan', 'Sedan'), ('other', 'Other')], default=None, max_length=20)),
                ('model', models.CharField(help_text='Vehicle Model', max_length=100)),
                ('plate', models.CharField(help_text='Vehicle plate (e.g ABC1D23)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$', 'Enter a valid plate (ABC1D23 format).')])),
                ('year', models.PositiveIntegerField(help_text='Manufacturing Year')),
                ('color', models.CharField(blank=True, choices=[('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('carbon', 'Carbon'), ('darkblue', 'Dark Blue'), ('darkgreen', 'Dark Green'), ('gold', 'Gold'), ('grafite', 'Grafite'), ('green', 'Green'), ('grey', 'Grey'), ('indigo', 'Indigo'), ('maroon', 'Maroon'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('red', 'Red'), ('silver', 'Silver'), ('violet', 'Violet'), ('white', 'White'), ('yellow', 'Yellow'), ('other', 'Other')], max_length=30)),
                ('capacity_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Load capacity in kilograms', max_digits=10, null=True)),
                ('capacity_m3_or_liters', models.DecimalField(blank=True, decimal_places=2, help_text='Volume capacity in cubic meters or liters', max_digits=10, null=True)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('gasoline', 'Gasoline'), ('ethanol', 'Ethanol'), ('flex', 'Flex'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='diesel', max_length=20)),
                ('chassis_number', models.CharField(max_length=50, unique=True, verbose_name='Chassis Number')),
                ('renavam', models.CharField(help_text='RENAVAM number', max_length=11, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'In Maintenance'), ('inactive', 'Inactive'), ('available', 'Available'), ('unavailable', 'Unavailable'), ('sold', 'Sold')], default='active', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_km', models.PositiveIntegerField(default=0, help_text='Current odometer reading')),
                ('last_maintenance_km', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('next_maintenance_km', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('estimated_days', models.PositiveIntegerField(default=1, help_text='Estimated duration in days (can be adjusted later)', verbose_name='Estimated Days')),
                ('workday_type', models.CharField(choices=[('daily_8h', 'Daily 8 hours'), ('daily_10h', 'Daily 10 hours'), ('daily_12h', 'Daily 12 hours'), ('transfer', 'Transfer'), ('custom', 'Custom')], default='daily_10h', help_text='Default type of workday for this assignment', max_length=20, verbose_name='Default Workday Type')),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Agreed daily rate value for this assignment', max_digits=10, verbose_name='Daily Rate')),
                ('total_days_worked', models.PositiveIntegerField(default=0, help_text='Total number of days actually worked', verbose_name='Total Days Worked')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount to pay for this assignment', max_digits=12, verbose_name='Total Amount')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(limit_choices_to={'employee_type': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='personnel.employee')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Assignment',
                'verbose_name_plural': 'Vehicle Assignments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignmentWorkday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date of the workday', verbose_name='Work Date')),
                ('start_time', models.TimeField(help_text='Work start time', verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, help_text='Work end time (leave emepty if ongoing)', null=True, verbose_name='End Time')),
                ('break_minutes', models.PositiveIntegerField(blank=True, default=0, help_text='Total break time in minutes', verbose_name='Break Minutes')),
                ('workday_type', models.CharField(choices=[('daily_8h', 'Daily 8 hours'), ('daily_10h', 'Daily 10 hours'), ('daily_12h', 'Daily 12 hours'), ('transfer', 'Transfer'), ('custom', 'Custom')], default='daily_10h', max_length=30, verbose_name='Workday Type')),
                ('standard_hours', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Standard Workday hours (8, 10 or 12h)', max_digits=10, max_length=4, verbose_name='Standard Hours')),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Value for the complete daily', max_digits=10, max_length=10, null=True, verbose_name='Daily Rate')),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total hours worked', max_digits=5, verbose_name='Total Hours')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overtime hours (after 15min tolerance)', max_digits=5, verbose_name='Overtime Hours')),
                ('daily_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount for daily rate', max_digits=10, verbose_name='Daily Amount')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount for overtime hours', max_digits=10, verbose_name='Overtime Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount to pay', max_digits=10, verbose_name='Total Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('payment_reference', models.CharField(blank=True, help_text='Payment transaction reference', max_length=100, verbose_name='Payment Reference')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_workdays', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='fleet.vehicleassignment', verbose_name='Assignment')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workday',
                'verbose_name_plural': 'Workdays',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Brand name (e.g., Jeep, Mercedes)', max_length=100)),
                ('country', models.CharField(blank=True, help_text='Country of origin', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='fleet/logos/brands')),
                ('is_active', models.BooleanField(default=True, help_text='Is this brand active?')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Brand',
                'verbose_name_plural': 'Vehicle Brands',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.vehiclebrand'),
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('crlv', 'CRLV (Vehicle Registration)'), ('insurance', 'Insurance'), ('antt', 'ANTT Registration'), ('inspection', 'Vehicle Inspection'), ('emission', 'Emission Certificate'), ('other', 'Other')], max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='fleet/vehicle_documents/')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Document',
                'verbose_name_plural': 'Vehicle Documents',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive Maintenance'), ('corrective', 'Corrective Maintenance'), ('inspection', 'Inspection'), ('tire_change', 'Tire Change'), ('oil_change', 'Oil Change'), ('brake_service', 'Brake Service'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=30)),
                ('scheduled_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField()),
                ('odometer_reading', models.PositiveIntegerField(help_text='odometer km at maintenance.')),
                ('next_maintenance_km', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('service_provider', models.CharField(blank=True, max_length=250)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('parts_replaced', models.TextField(blank=True, help_text='List of parts replaced.')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'verbose_name_plural': 'Maintenance Records',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['vehicle', 'status'], name='fleet_maint_vehicle_f43fe7_idx'), models.Index(fields=['scheduled_date'], name='fleet_maint_schedul_8d88d3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='vehicleassignment',
            index=models.Index(fields=['vehicle', 'is_active'], name='fleet_vehic_vehicle_4a38f8_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignment',
            index=models.Index(fields=['driver', 'is_active'], name='fleet_vehic_driver__4d4c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignmentworkday',
            index=models.Index(fields=['tenant', 'date'], name='fleet_vehic_tenant__c8d0df_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignmentworkday',
            index=models.Index(fields=['assignment', 'status'], name='fleet_vehic_assignm_161663_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignmentworkday',
            index=models.Index(fields=['status'], name='fleet_vehic_status_4c7b99_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleassignmentworkday',
            unique_together={('assignment', 'date')},
        ),
        migrations.AddIndex(
            model_name='vehiclebrand',
            index=models.Index(fields=['tenant', 'name'], name='fleet_vehic_tenant__a963ee_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclebrand',
            index=models.Index(fields=['is_active'], name='fleet_vehic_is_acti_1c61eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclebrand',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['tenant', 'status'], name='fleet_vehic_tenant__6f675a_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['plate'], name='fleet_vehic_plate_7d010e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledocument',
            index=models.Index(fields=['vehicle', 'document_type'], name='fleet_vehic_vehicle_89df13_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledocument',
            index=models.Index(fields=['expiry_date'], name='fleet_vehic_expiry__020259_idx'),
        ),
    ]
