# Generated by Django 5.2.6 on 2026-02-04 21:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('personnel', '0003_alter_employee_birth_date'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkdayApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField(help_text='First workday date in this approval', verbose_name='Period Start')),
                ('period_end', models.DateField(help_text='Last workday date in this approval', verbose_name='Period End')),
                ('total_workdays', models.PositiveIntegerField(default=0, verbose_name='Total Workdays')),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Hours Worked')),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Overtime Hours Worked')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workday_approvals_made', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays_approvals', to='fleet.vehicleassignment')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workday Approval',
                'verbose_name_plural': 'Workday Approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vehicleassignmentworkday',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workdays', to='fleet.workdayapproval', verbose_name='Approval Batch'),
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_number', models.CharField(max_length=50, unique=True, verbose_name='Report Number')),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('sent', 'Sent to E-mail'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='generated', max_length=30, verbose_name='Situação')),
                ('sent_to_company_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent to Company At')),
                ('sent_to_driver_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent to Driver At')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='fleet/work_reports/', verbose_name='PDF Report')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approval', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_report', to='fleet.workdayapproval', verbose_name='Approval')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to='fleet.vehicleassignment', verbose_name='Assignment')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Report',
                'verbose_name_plural': 'Work Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='Payment Number')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gross Amount')),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Deductions')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved for Payment'), ('processing', 'Processing'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('pix', 'PIX'), ('cash', 'Cash'), ('check', 'Check')], max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('payment_reference', models.CharField(blank=True, help_text='Bank transaction ID, PIX key, etc', max_length=200, verbose_name='Payment Reference')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='fleet/payment_receipts/', verbose_name='Payment Receipt')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='fleet.vehicleassignment', verbose_name='Assignment')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='personnel.employee', verbose_name='Driver')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL, verbose_name='Paid By')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='fleet.workreport', verbose_name='Work Report')),
            ],
            options={
                'verbose_name': 'Payment Order',
                'verbose_name_plural': 'Payment Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_number', models.CharField(max_length=50, unique=True, verbose_name='Report Number')),
                ('client_name', models.CharField(max_length=200, verbose_name='Client Name')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Client Email')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount')),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('sent', 'Sent'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='generated', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('client_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Client Approved At')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='fleet/expense_reports/', verbose_name='PDF Report')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('client_notes', models.TextField(blank=True, verbose_name='Client Notes')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_reports', to='fleet.vehicleassignment')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('payment_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense_report', to='fleet.paymentorder')),
            ],
            options={
                'verbose_name': 'Expense Report',
                'verbose_name_plural': 'Expense Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assignment', 'status'], name='fleet_expen_assignm_d66876_idx'), models.Index(fields=['report_number'], name='fleet_expen_report__5c43b2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workdayapproval',
            index=models.Index(fields=['assignment', 'status'], name='fleet_workd_assignm_fed17f_idx'),
        ),
        migrations.AddIndex(
            model_name='workdayapproval',
            index=models.Index(fields=['period_start', 'period_end'], name='fleet_workd_period__1220ba_idx'),
        ),
        migrations.AddIndex(
            model_name='workreport',
            index=models.Index(fields=['assignment', 'status'], name='fleet_workr_assignm_ec0b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='workreport',
            index=models.Index(fields=['report_number'], name='fleet_workr_report__de830e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['driver', 'status'], name='fleet_payme_driver__1f46ff_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['payment_number'], name='fleet_payme_payment_f318c5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', 'approved_at'], name='fleet_payme_status_27c021_idx'),
        ),
    ]
