# Generated by Django 5.2.6 on 2025-12-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_vehiclebrand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(choices=[('alfa_romeo', 'Alfa Romeo'), ('aston_martin', 'Aston Martin'), ('audi', 'Audi'), ('bentley', 'Bentley'), ('bmw', 'BMW'), ('bugatti', 'Bugatti'), ('byd', 'BYD'), ('chery', 'Chery'), ('chevrolet', 'Chevrolet'), ('citroen', 'Citroën'), ('dacia', 'Dacia'), ('ferrari', 'Ferrari'), ('fiat', 'Fiat'), ('ford', 'Ford'), ('geely', 'Geely'), ('great_wall', 'Great Wall'), ('honda', 'Honda'), ('hyundai', 'Hyundai'), ('jaguar', 'Jaguar'), ('kia', 'Kia'), ('lamborghini', 'Lamborghini'), ('land_rover', 'Land Rover'), ('maserati', 'Maserati'), ('mazda', 'Mazda'), ('mercedes_benz', 'Mercedes-Benz'), ('mitsubishi', 'Mitsubishi'), ('nissan', 'Nissan'), ('peugeot', 'Peugeot'), ('porsche', 'Porsche'), ('renault', 'Renault'), ('rolls_royce', 'Rolls-Royce'), ('saab', 'Saab'), ('seat', 'SEAT'), ('skoda', 'Škoda'), ('subaru', 'Subaru'), ('suzuki', 'Suzuki'), ('tesla', 'Tesla'), ('toyota', 'Toyota'), ('volkswagen', 'Volkswagen'), ('volvo', 'Volvo'), ('ashok_leyland', 'Ashok Leyland'), ('caio', 'Caio'), ('daf', 'DAF'), ('freightliner', 'Freightliner'), ('hino', 'Hino'), ('international', 'International'), ('iveco', 'Iveco'), ('kenworth', 'Kenworth'), ('mack', 'Mack'), ('man', 'MAN'), ('marcopolo', 'Marcopolo'), ('mercedes_trucks', 'Mercedes-Benz Trucks'), ('neobus', 'Neobus'), ('peterbilt', 'Peterbilt'), ('scania', 'Scania'), ('tata', 'Tata Motors'), ('volvo_trucks', 'Volvo Trucks'), ('yutong', 'Yutong'), ('aprilia', 'Aprilia'), ('bajaj', 'Bajaj'), ('ducati', 'Ducati'), ('harley_davidson', 'Harley-Davidson'), ('honda_moto', 'Honda (Motos)'), ('kawasaki', 'Kawasaki'), ('ktm', 'KTM'), ('mv_agusta', 'MV Agusta'), ('piaggio', 'Piaggio'), ('royal_enfield', 'Royal Enfield'), ('suzuki_moto', 'Suzuki (Motos)'), ('triumph', 'Triumph'), ('vespa', 'Vespa'), ('yamaha', 'Yamaha')], max_length=50),
        ),
    ]
