# Generated by Django 5.2.6 on 2025-12-19 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_vehicle_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.vehiclebrand'),
        ),
        migrations.AlterField(
            model_name='vehiclebrand',
            name='name',
            field=models.CharField(help_text='Brand name (e.g., Jeep, Mercedes)', max_length=100),
        ),
    ]
