# Generated by Django 5.2.6 on 2025-12-19 03:37

import fleet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_vehicle_brand_alter_vehiclebrand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, help_text='Vehicle photo', null=True, upload_to=fleet.models.Vehicle.vehicle_photo_path),
        ),
    ]
