# Generated by Django 5.2.6 on 2025-12-27 01:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_vehicle_photo'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleassignment',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Agreed daily rate value for this assignment', max_digits=10, verbose_name='Daily Rate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='estimated_days',
            field=models.PositiveIntegerField(default=1, help_text='Estimated duration in days (can be adjusted later)', verbose_name='Estimated Days'),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount to pay for this assignment', max_digits=12, verbose_name='Total Amount'),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='total_days_worked',
            field=models.PositiveIntegerField(default=0, help_text='Total number of days actually worked', verbose_name='Total Days Worked'),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='workday_type',
            field=models.CharField(choices=[('daily_8h', 'Daily 8 hours'), ('daily_10h', 'Daily 10 hours'), ('daily_12h', 'Daily 12 hours'), ('transfer', 'Transfer'), ('custom', 'Custom')], default='daily_10h', help_text='Default type of workday for this assignment', max_length=20, verbose_name='Default Workday Type'),
        ),
        migrations.CreateModel(
            name='VehicleAssignmentWorkday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date of the workday', verbose_name='Work Date')),
                ('start_time', models.TimeField(help_text='Work start time', verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, help_text='Work end time (leave emepty if ongoing)', null=True, verbose_name='End Time')),
                ('break_minutes', models.PositiveIntegerField(blank=True, default=0, help_text='Total break time in minutes', verbose_name='Break Minutes')),
                ('workday_type', models.CharField(choices=[('daily_8h', 'Daily 8 hours'), ('daily_10h', 'Daily 10 hours'), ('daily_12h', 'Daily 12 hours'), ('transfer', 'Transfer'), ('custom', 'Custom')], default='daily_10h', max_length=30, verbose_name='Workday Type')),
                ('standard_hours', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Standard Workday hours (8, 10 or 12h)', max_digits=10, max_length=4, verbose_name='Standard Hours')),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Value for the complete daily', max_digits=10, max_length=10, verbose_name='Daily Rate')),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total hours worked', max_digits=5, verbose_name='Total Hours')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overtime hours (after 15min tolerance)', max_digits=5, verbose_name='Overtime Hours')),
                ('daily_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount for daily rate', max_digits=10, verbose_name='Daily Amount')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount for overtime hours', max_digits=10, verbose_name='Overtime Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount to pay', max_digits=10, verbose_name='Total Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('payment_reference', models.CharField(blank=True, help_text='Payment transaction reference', max_length=100, verbose_name='Payment Reference')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_workdays', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='fleet.vehicleassignment', verbose_name='Assignment')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workday',
                'verbose_name_plural': 'Workdays',
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['tenant', 'date'], name='fleet_vehic_tenant__c8d0df_idx'), models.Index(fields=['assignment', 'status'], name='fleet_vehic_assignm_161663_idx'), models.Index(fields=['status'], name='fleet_vehic_status_4c7b99_idx')],
                'unique_together': {('assignment', 'date')},
            },
        ),
    ]
