# Generated by Django 5.2.6 on 2025-12-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_vehicleassignment_daily_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleassignmentworkday',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Value for the complete daily', max_digits=10, max_length=10, null=True, verbose_name='Daily Rate'),
        ),
    ]
