# Generated by Django 5.2.6 on 2026-01-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_alter_vehicleassignmentworkday_daily_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='capacity_m3_or_liters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume capacity in cubic meters or liters', max_digits=10, null=True),
        ),
    ]
